import type { AppLanguage } from './language'
import { defaultAppLanguage } from './language'

const englishMessages = {
  'window.untitled': 'Untitled',
  'workspace.sidebarAriaLabel': 'Workspace sidebar',
  'settings.title': 'Settings',
  'settings.close': 'Close settings',
  'settings.language': 'Language',
  'settings.applicationTheme': 'Application Theme',
  'settings.documentTheme': 'Document Theme',
  'settings.documentThemeHelper': 'Custom uses the CSS you import from the Theme menu.',
  'settings.editorFont': 'Editor Font',
  'settings.editorFontSize': 'Editor Font Size',
  'language.option.zh-CN': '中文',
  'language.option.en': 'English',
  'option.system': 'System',
  'option.light': 'Light',
  'option.dark': 'Dark',
  'option.default': 'Default',
  'option.elegant': 'Elegant',
  'option.newsprint': 'Newsprint',
  'option.custom': 'Custom',
  'option.systemSans': 'System Sans',
  'option.serif': 'Serif',
  'option.monospace': 'Monospace',
  'sidebar.tab.files': 'FILES',
  'sidebar.tab.outline': 'OUTLINE',
  'sidebar.search.placeholder': 'Search notes',
  'sidebar.more.open': 'More actions',
  'sidebar.more.close': 'Close more actions',
  'sidebar.action.openFolder': 'Open Folder...',
  'sidebar.action.refreshWorkspace': 'Refresh Workspace',
  'sidebar.action.closeWorkspace': 'Close Workspace',
  'sidebar.action.createNote': 'Create new note',
  'sidebar.workspace.none': 'No workspace',
  'sidebar.workspace.openFolderHint': 'Open a folder to browse notes',
  'sidebar.empty.title': 'No workspace open',
  'sidebar.empty.copy':
    'Open a folder to keep navigation nearby without turning Mako into a heavy workspace app.',
  'sidebar.loading.generic': 'Loading...',
  'sidebar.loading.workspace': 'Loading workspace...',
  'sidebar.loading.search': 'Searching notes...',
  'sidebar.retry': 'Retry',
  'sidebar.empty.folder': 'Empty',
  'sidebar.noSupportedFiles': 'No supported files in this folder yet.',
  'sidebar.search.noResults': 'No notes match this search.',
  'sidebar.search.fileNameMatch': 'File name match',
  'sidebar.search.lineMatch': 'L{lineNumber}  {excerpt}',
  'sidebar.outline.openNote': 'Open a note to see its outline.',
  'sidebar.outline.noHeadings': 'No headings in this note.',
  'sidebar.context.rename': 'Rename',
  'sidebar.context.delete': 'Delete',
  'sidebar.error.readDirectoryFallback': 'Failed to read this directory.',
  'sidebar.error.readWorkspaceFallback': 'Failed to read this workspace folder.',
  'sidebar.error.readEntry': 'Could not read "{name}". {error}',
  'sidebar.error.readWorkspace': 'Could not read this workspace folder. {error}',
  'sidebar.error.searchFailed': 'Search failed. {error}',
  'math.label': 'Formula',
  'math.placeholder': 'Type LaTeX...',
  'math.empty': 'Empty formula',
  'mermaid.label': 'Mermaid Source',
  'mermaid.placeholder': 'Type Mermaid diagram source...',
  'mermaid.empty': 'Empty Mermaid diagram.',
  'mermaid.renderFailed': 'Mermaid render failed.\n\n{message}\n\n{source}',
  'editor.defaultContentTitle': 'Welcome to Mako',
  'editor.defaultContentBody': 'Start typing here...',
  'dialog.unsavedChanges.message': 'You have unsaved changes.',
  'dialog.discardChanges.title': 'Discard Changes?',
  'dialog.button.discardChanges': 'Discard Changes',
  'dialog.button.cancel': 'Cancel',
  'dialog.detail.discardOnClose': 'Closing this window will discard the current draft.',
  'dialog.detail.discardOnNewDraft': 'Creating a new draft here will discard the current draft.',
  'dialog.detail.discardOnOpenOtherFile':
    'Opening another file here will discard the current draft.',
  'dialog.detail.discardOnCreateNote': 'Creating a new note here will discard the current draft.',
  'dialog.reload.title': 'Reload from Disk?',
  'dialog.reload.message': 'This file changed on disk.',
  'dialog.reload.detail': 'Reloading will discard your unsaved edits in Mako.',
  'dialog.button.reloadFromDisk': 'Reload from Disk',
  'dialog.button.keepMyChanges': 'Keep My Changes',
  'dialog.deleteNote.title': 'Delete Note?',
  'dialog.deleteNote.message': 'Delete {name}?',
  'dialog.deleteNote.detailClean': 'Deleting this note will permanently remove it from disk.',
  'dialog.deleteNote.detailDirty':
    'Deleting this note will permanently remove it from disk and discard your unsaved edits.',
  'dialog.button.delete': 'Delete',
  'dialog.openFile.title': 'Open File',
  'dialog.openFolder.title': 'Open Folder',
  'dialog.saveFile.title': 'Save File',
  'dialog.exportPdf.title': 'Export PDF',
  'dialog.importCustomTheme.title': 'Import Custom Theme',
  'filter.markdown': 'Markdown',
  'filter.text': 'Text',
  'filter.allFiles': 'All Files',
  'filter.pdf': 'PDF',
  'filter.css': 'CSS',
  'error.openFailed.title': 'Open Failed',
  'error.openFailed.named': 'Could not open {name}.\n\n{message}',
  'error.openFailed.selectedFile': 'Could not open the selected file.\n\n{message}',
  'error.saveFailed.title': 'Save Failed',
  'error.saveFailed.named': 'Could not save {name}.\n\n{message}',
  'error.exportFailed.title': 'Export Failed',
  'error.exportFailed.message': 'Could not export the PDF.\n\n{message}',
  'error.themeImportFailed.title': 'Theme Import Failed',
  'error.themeImportFailed.message': 'Could not load the selected theme.\n\n{message}',
  'error.createFailed.title': 'Create Failed',
  'error.createFailed.named': 'Could not create {name}.\n\n{message}',
  'error.createFailed.newNote': 'Could not create a new note.\n\n{message}',
  'error.createFailed.availableName':
    'Could not find an available name for a new note in this folder.',
  'error.renameFailed.title': 'Rename Failed',
  'error.renameFailed.named': 'Could not rename {name}.\n\n{message}',
  'error.deleteFailed.title': 'Delete Failed',
  'error.deleteFailed.named': 'Could not delete {name}.\n\n{message}',
  'error.deleteFailed.alreadyOpen': '{name} is already open in another window.',
  'error.rename.emptyName': 'The file name cannot be empty.',
  'error.rename.withinFolder': 'The file name must stay within the current folder.',
  'error.rename.keepSupportedExtension':
    'The renamed file must keep a supported Markdown or text extension.',
  'error.fileAlreadyOpenInAnotherWindow': '{name} is already open in another window.',
  'error.workspace.onlyFilesCanBeDeleted': 'Only files can be deleted from the workspace.',
  'menu.settings': 'Settings…',
  'menu.root.file': 'File',
  'menu.root.edit': 'Edit',
  'menu.root.view': 'View',
  'menu.root.theme': 'Theme',
  'menu.root.help': 'Help',
  'menu.new': 'New',
  'menu.open': 'Open...',
  'menu.openFolder': 'Open Folder...',
  'menu.closeWorkspace': 'Close Workspace',
  'menu.refreshWorkspace': 'Refresh Workspace',
  'menu.save': 'Save',
  'menu.saveAs': 'Save As...',
  'menu.exportPdf': 'Export PDF...',
  'menu.toggleSidebar': 'Toggle Sidebar',
  'menu.showOutline': 'Show Outline',
  'menu.toggleSourceMode': 'Toggle Source Mode',
  'menu.applicationTheme': 'Application Theme',
  'menu.documentTheme': 'Document Theme',
  'menu.importCustomTheme': 'Import Custom Theme...',
  'menu.aboutMako': 'About Mako'
} as const

const chineseMessages: Record<keyof typeof englishMessages, string> = {
  'window.untitled': '未命名',
  'workspace.sidebarAriaLabel': '工作区侧边栏',
  'settings.title': '设置',
  'settings.close': '关闭设置',
  'settings.language': '语言',
  'settings.applicationTheme': '应用主题',
  'settings.documentTheme': '文档主题',
  'settings.documentThemeHelper': '自定义会使用你从“主题”菜单导入的 CSS。',
  'settings.editorFont': '编辑器字体',
  'settings.editorFontSize': '编辑器字号',
  'language.option.zh-CN': '中文',
  'language.option.en': 'English',
  'option.system': '跟随系统',
  'option.light': '浅色',
  'option.dark': '深色',
  'option.default': '默认',
  'option.elegant': '典雅',
  'option.newsprint': '报刊',
  'option.custom': '自定义',
  'option.systemSans': '系统无衬线',
  'option.serif': '衬线',
  'option.monospace': '等宽',
  'sidebar.tab.files': '文件',
  'sidebar.tab.outline': '大纲',
  'sidebar.search.placeholder': '搜索笔记',
  'sidebar.more.open': '更多操作',
  'sidebar.more.close': '收起更多操作',
  'sidebar.action.openFolder': '打开文件夹...',
  'sidebar.action.refreshWorkspace': '刷新工作区',
  'sidebar.action.closeWorkspace': '关闭工作区',
  'sidebar.action.createNote': '新建笔记',
  'sidebar.workspace.none': '未打开工作区',
  'sidebar.workspace.openFolderHint': '打开文件夹后即可浏览笔记',
  'sidebar.empty.title': '未打开工作区',
  'sidebar.empty.copy': '打开一个文件夹，把导航留在身边，同时保持 Mako 的轻量体验。',
  'sidebar.loading.generic': '加载中...',
  'sidebar.loading.workspace': '正在加载工作区...',
  'sidebar.loading.search': '正在搜索笔记...',
  'sidebar.retry': '重试',
  'sidebar.empty.folder': '空文件夹',
  'sidebar.noSupportedFiles': '这个文件夹里还没有受支持的文件。',
  'sidebar.search.noResults': '没有找到匹配的笔记。',
  'sidebar.search.fileNameMatch': '文件名匹配',
  'sidebar.search.lineMatch': '第 {lineNumber} 行  {excerpt}',
  'sidebar.outline.openNote': '打开一篇笔记即可查看大纲。',
  'sidebar.outline.noHeadings': '这篇笔记里还没有标题。',
  'sidebar.context.rename': '重命名',
  'sidebar.context.delete': '删除',
  'sidebar.error.readDirectoryFallback': '无法读取此目录。',
  'sidebar.error.readWorkspaceFallback': '无法读取这个工作区文件夹。',
  'sidebar.error.readEntry': '无法读取“{name}”。{error}',
  'sidebar.error.readWorkspace': '无法读取这个工作区文件夹。{error}',
  'sidebar.error.searchFailed': '搜索失败。{error}',
  'math.label': '公式',
  'math.placeholder': '输入 LaTeX...',
  'math.empty': '暂无公式',
  'mermaid.label': 'Mermaid 源码',
  'mermaid.placeholder': '输入 Mermaid 图表源码...',
  'mermaid.empty': '暂无 Mermaid 图表。',
  'mermaid.renderFailed': 'Mermaid 渲染失败。\n\n{message}\n\n{source}',
  'editor.defaultContentTitle': '欢迎使用 Mako',
  'editor.defaultContentBody': '在这里开始写作...',
  'dialog.unsavedChanges.message': '你有未保存的更改。',
  'dialog.discardChanges.title': '放弃更改？',
  'dialog.button.discardChanges': '放弃更改',
  'dialog.button.cancel': '取消',
  'dialog.detail.discardOnClose': '关闭此窗口会丢弃当前草稿。',
  'dialog.detail.discardOnNewDraft': '在这里新建草稿会丢弃当前草稿。',
  'dialog.detail.discardOnOpenOtherFile': '在这里打开其他文件会丢弃当前草稿。',
  'dialog.detail.discardOnCreateNote': '在这里新建笔记会丢弃当前草稿。',
  'dialog.reload.title': '从磁盘重新加载？',
  'dialog.reload.message': '这个文件在磁盘上已发生变化。',
  'dialog.reload.detail': '重新加载会丢弃你在 Mako 中未保存的修改。',
  'dialog.button.reloadFromDisk': '从磁盘重新加载',
  'dialog.button.keepMyChanges': '保留我的修改',
  'dialog.deleteNote.title': '删除笔记？',
  'dialog.deleteNote.message': '删除“{name}”？',
  'dialog.deleteNote.detailClean': '删除后会将这篇笔记从磁盘中永久移除。',
  'dialog.deleteNote.detailDirty': '删除后会将这篇笔记从磁盘中永久移除，并丢弃你未保存的修改。',
  'dialog.button.delete': '删除',
  'dialog.openFile.title': '打开文件',
  'dialog.openFolder.title': '打开文件夹',
  'dialog.saveFile.title': '保存文件',
  'dialog.exportPdf.title': '导出 PDF',
  'dialog.importCustomTheme.title': '导入自定义主题',
  'filter.markdown': 'Markdown',
  'filter.text': '文本',
  'filter.allFiles': '所有文件',
  'filter.pdf': 'PDF',
  'filter.css': 'CSS',
  'error.openFailed.title': '打开失败',
  'error.openFailed.named': '无法打开 {name}。\n\n{message}',
  'error.openFailed.selectedFile': '无法打开所选文件。\n\n{message}',
  'error.saveFailed.title': '保存失败',
  'error.saveFailed.named': '无法保存 {name}。\n\n{message}',
  'error.exportFailed.title': '导出失败',
  'error.exportFailed.message': '无法导出 PDF。\n\n{message}',
  'error.themeImportFailed.title': '主题导入失败',
  'error.themeImportFailed.message': '无法加载所选主题。\n\n{message}',
  'error.createFailed.title': '创建失败',
  'error.createFailed.named': '无法创建 {name}。\n\n{message}',
  'error.createFailed.newNote': '无法新建笔记。\n\n{message}',
  'error.createFailed.availableName': '无法在当前文件夹中找到可用的新笔记名称。',
  'error.renameFailed.title': '重命名失败',
  'error.renameFailed.named': '无法重命名 {name}。\n\n{message}',
  'error.deleteFailed.title': '删除失败',
  'error.deleteFailed.named': '无法删除 {name}。\n\n{message}',
  'error.deleteFailed.alreadyOpen': '{name} 已在另一个窗口中打开。',
  'error.rename.emptyName': '文件名不能为空。',
  'error.rename.withinFolder': '文件名必须保留在当前文件夹内。',
  'error.rename.keepSupportedExtension': '重命名后的文件必须保留受支持的 Markdown 或文本扩展名。',
  'error.fileAlreadyOpenInAnotherWindow': '{name} 已在另一个窗口中打开。',
  'error.workspace.onlyFilesCanBeDeleted': '只能从工作区中删除文件。',
  'menu.settings': '设置…',
  'menu.root.file': '文件',
  'menu.root.edit': '编辑',
  'menu.root.view': '视图',
  'menu.root.theme': '主题',
  'menu.root.help': '帮助',
  'menu.new': '新建',
  'menu.open': '打开...',
  'menu.openFolder': '打开文件夹...',
  'menu.closeWorkspace': '关闭工作区',
  'menu.refreshWorkspace': '刷新工作区',
  'menu.save': '保存',
  'menu.saveAs': '另存为...',
  'menu.exportPdf': '导出 PDF...',
  'menu.toggleSidebar': '切换侧边栏',
  'menu.showOutline': '显示大纲',
  'menu.toggleSourceMode': '切换源码模式',
  'menu.applicationTheme': '应用主题',
  'menu.documentTheme': '文档主题',
  'menu.importCustomTheme': '导入自定义主题...',
  'menu.aboutMako': '关于 Mako'
}

const messages: Record<AppLanguage, Record<keyof typeof englishMessages, string>> = {
  'zh-CN': chineseMessages,
  en: englishMessages
}

export type TranslationKey = keyof typeof englishMessages
export type TranslationValues = Record<string, string | number>

export function translateApp(
  language: AppLanguage,
  key: TranslationKey,
  values: TranslationValues = {}
): string {
  const template = messages[language]?.[key] ?? messages[defaultAppLanguage][key] ?? key
  return template.replace(/\{(\w+)\}/g, (_match, token: string) => {
    return Object.prototype.hasOwnProperty.call(values, token) ? String(values[token]) : `{${token}}`
  })
}
